/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationRequest } from '../models/notification-request';
export interface BlogRequest {
  description?: string;
  notificationRequest?: NotificationRequest;
  text?: string;
  title?: string;
}
