/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlogResponse {
  author?: string;
  coverImage?: Array<string>;
  description?: string;
  id?: number;
  text?: string;
  title?: string;
  viewCount?: number;
}
