/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationRequest {
  message?: string;
  summary?: string;
  title?: string;
  url?: string;
}
