/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBlogResponse } from '../../models/api-response-blog-response';

export interface GetById$Params {
  'blog-id': number;
}

export function getById(http: HttpClient, rootUrl: string, params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBlogResponse>> {
  const rb = new RequestBuilder(rootUrl, getById.PATH, 'get');
  if (params) {
    rb.path('blog-id', params['blog-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBlogResponse>;
    })
  );
}

getById.PATH = '/blogs/{blog-id}';
