/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBlogResponse } from '../../models/api-response-blog-response';
import { BlogRequest } from '../../models/blog-request';

export interface CreateBlog$Params {
      body: BlogRequest
}

export function createBlog(http: HttpClient, rootUrl: string, params: CreateBlog$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBlogResponse>> {
  const rb = new RequestBuilder(rootUrl, createBlog.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBlogResponse>;
    })
  );
}

createBlog.PATH = '/admin/blogs';
