/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BlogResponse } from '../models/blog-response';
import { createBlog } from '../fn/admin-controller/create-blog';
import { CreateBlog$Params } from '../fn/admin-controller/create-blog';
import { deleteBlog } from '../fn/admin-controller/delete-blog';
import { DeleteBlog$Params } from '../fn/admin-controller/delete-blog';
import { test1 } from '../fn/admin-controller/test-1';
import { Test1$Params } from '../fn/admin-controller/test-1';
import { updateBlog } from '../fn/admin-controller/update-blog';
import { UpdateBlog$Params } from '../fn/admin-controller/update-blog';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateBlog()` */
  static readonly UpdateBlogPath = '/admin/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBlog()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBlog$Response(params: UpdateBlog$Params, context?: HttpContext): Observable<StrictHttpResponse<BlogResponse>> {
    return updateBlog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBlog$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBlog(params: UpdateBlog$Params, context?: HttpContext): Observable<BlogResponse> {
    return this.updateBlog$Response(params, context).pipe(
      map((r: StrictHttpResponse<BlogResponse>): BlogResponse => r.body)
    );
  }

  /** Path part for operation `createBlog()` */
  static readonly CreateBlogPath = '/admin/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBlog()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBlog$Response(params: CreateBlog$Params, context?: HttpContext): Observable<StrictHttpResponse<BlogResponse>> {
    return createBlog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBlog$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBlog(params: CreateBlog$Params, context?: HttpContext): Observable<BlogResponse> {
    return this.createBlog$Response(params, context).pipe(
      map((r: StrictHttpResponse<BlogResponse>): BlogResponse => r.body)
    );
  }

  /** Path part for operation `deleteBlog()` */
  static readonly DeleteBlogPath = '/admin/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteBlog()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBlog$Response(params: DeleteBlog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteBlog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteBlog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBlog(params: DeleteBlog$Params, context?: HttpContext): Observable<void> {
    return this.deleteBlog$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `test1()` */
  static readonly Test1Path = '/admin/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `test1()` instead.
   *
   * This method doesn't expect any request body.
   */
  test1$Response(params?: Test1$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return test1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `test1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  test1(params?: Test1$Params, context?: HttpContext): Observable<string> {
    return this.test1$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
