/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { subscribe } from '../fn/subscription-controller/subscribe';
import { Subscribe$Params } from '../fn/subscription-controller/subscribe';

@Injectable({ providedIn: 'root' })
export class SubscriptionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `subscribe()` */
  static readonly SubscribePath = '/user/subscriptions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `subscribe()` instead.
   *
   * This method doesn't expect any request body.
   */
  subscribe$Response(params: Subscribe$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return subscribe(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `subscribe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  subscribe(params: Subscribe$Params, context?: HttpContext): Observable<{
}> {
    return this.subscribe$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
